# Generated by Django 3.1.6 on 2021-05-16 12:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210516_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, editable=False, max_length=30, unique=True),
        ),
    ]
