# Generated by Django 3.1.6 on 2021-05-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationlinks',
            name='token',
            field=models.CharField(default='b09bnlpxtku3l3uy6830l91xuzbqcewazvhh56iygalc3hxuui', max_length=50, null=True, unique=True),
        ),
    ]
