# Generated by Django 3.1.6 on 2021-05-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20210516_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationlinks',
            name='token',
            field=models.CharField(default='eovmqmikwiufo5rjz32oybafyeuc83guxbhp7eyjwngvbtexjl', max_length=50, null=True, unique=True),
        ),
    ]
