# Generated by Django 3.1.6 on 2021-05-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20210516_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationlinks',
            name='token',
            field=models.CharField(default='7m40zgqx3n6r776ltrqwtwi1gne258rj0kflt1i0npwmv196r1', max_length=50, null=True, unique=True),
        ),
    ]
