# Generated by Django 3.1.6 on 2021-05-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20210516_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationlinks',
            name='token',
            field=models.CharField(default='fd1e7g6x73wmavz7oistaiyt4r76rdgkx22d6yuql7aomkv5zy', max_length=50, null=True, unique=True),
        ),
    ]
